/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "auth.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void (*)(int)
#endif

static void
auth_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		rpc_client req_authorization_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case REQ_AUTHORIZATION:
		_xdr_argument = (xdrproc_t)xdr_rpc_client;
		_xdr_result = (xdrproc_t)xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *))req_authorization_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void
auth_prog_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		rpc_client req_acc_token_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case REQ_ACC_TOKEN:
		_xdr_argument = (xdrproc_t)xdr_rpc_client;
		_xdr_result = (xdrproc_t)xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *))req_acc_token_2_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void
auth_prog_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		rpc_client validate_delegate_action_3_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case VALIDATE_DELEGATE_ACTION:
		_xdr_argument = (xdrproc_t)xdr_rpc_client;
		_xdr_result = (xdrproc_t)xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *))validate_delegate_action_3_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void
auth_prog_4(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		rpc_client approve_request_token_4_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case APPROVE_REQUEST_TOKEN:
		_xdr_argument = (xdrproc_t)xdr_rpc_client;
		_xdr_result = (xdrproc_t)xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *))approve_request_token_4_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

int main(int argc, char **argv)
{
	/* O condiție necesară pentru a executa server-ul ce implementează modelul Oauth */
	if (argc != 5)
	{
		printf("[SERVER] Pass 5 correct arguments for this Oauth server...\n");
		exit(1);
	}

	register SVCXPRT *transp;
	setbuf(stdout, NULL);

	pmap_unset(AUTH_PROG, REQ_AUTH_VERSION);
	pmap_unset(AUTH_PROG, REQ_ACC_VERSION);
	pmap_unset(AUTH_PROG, VAL_DELG_VERSION);
	pmap_unset(AUTH_PROG, APPR_REQ_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL)
	{
		fprintf(stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, AUTH_PROG, REQ_AUTH_VERSION, auth_prog_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (AUTH_PROG, REQ_AUTH_VERSION, udp).");
		exit(1);
	}
	if (!svc_register(transp, AUTH_PROG, REQ_ACC_VERSION, auth_prog_2, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (AUTH_PROG, REQ_ACC_VERSION, udp).");
		exit(1);
	}
	if (!svc_register(transp, AUTH_PROG, VAL_DELG_VERSION, auth_prog_3, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (AUTH_PROG, VAL_DELG_VERSION, udp).");
		exit(1);
	}
	if (!svc_register(transp, AUTH_PROG, APPR_REQ_VERSION, auth_prog_4, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (AUTH_PROG, APPR_REQ_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL)
	{
		fprintf(stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, AUTH_PROG, REQ_AUTH_VERSION, auth_prog_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (AUTH_PROG, REQ_AUTH_VERSION, tcp).");
		exit(1);
	}
	if (!svc_register(transp, AUTH_PROG, REQ_ACC_VERSION, auth_prog_2, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (AUTH_PROG, REQ_ACC_VERSION, tcp).");
		exit(1);
	}
	if (!svc_register(transp, AUTH_PROG, VAL_DELG_VERSION, auth_prog_3, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (AUTH_PROG, VAL_DELG_VERSION, tcp).");
		exit(1);
	}
	if (!svc_register(transp, AUTH_PROG, APPR_REQ_VERSION, auth_prog_4, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (AUTH_PROG, APPR_REQ_VERSION, tcp).");
		exit(1);
	}

	/* Variabila globală ce modelează proprietățile server-ului */
	rpc_sv = (rpc_server *)malloc(sizeof(rpc_server));

	/* Referințele către fișierele de intrare ce vor permite popularea unor liste
	   înlănțuite cu informațiile necesare */
	FILE *users_file = fopen(argv[1], "r");
	FILE *resources = fopen(argv[2], "r");
	FILE *users_permissions = fopen(argv[3], "r");
	avl_op = atoi(argv[4]);

	/* Inițializarea listelor înlănțuite ce vor fi folosite în cadrul funcțiilor */
	rpc_sv->acc_tokens = init_list();
	rpc_sv->users_id = init_list();
	rpc_sv->resources = init_list();
	rpc_sv->users_permissions = init_list();

	/* Se citesc liniile din fișierele de interes */
	read_file_list(users_file, rpc_sv->users_id, 1);
	read_file_list(resources, rpc_sv->resources, 2);
	read_file_list(users_permissions, rpc_sv->users_permissions, 3);

	/* Variabila globală ce reprezintă o referință către lista de permisiuni */
	iter_users_perm = rpc_sv->users_permissions->head;

	svc_run();
	fprintf(stderr, "%s", "svc_run returned");
	exit(1);
	/* NOTREACHED */
}
