/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "auth.h"

bool_t
xdr_string_l(XDR *xdrs, string_l *objp)
{

	if (!xdr_string(xdrs, objp, ~0))
		return FALSE;
	return TRUE;
}

bool_t
xdr_list_node(XDR *xdrs, list_node *objp)
{

	if (!xdr_pointer(xdrs, (char **)&objp->next, sizeof(list_node), (xdrproc_t)xdr_list_node))
		return FALSE;
	if (!xdr_pointer(xdrs, (char **)&objp->prev, sizeof(list_node), (xdrproc_t)xdr_list_node))
		return FALSE;
	if (!xdr_string(xdrs, &objp->data, ~0))
		return FALSE;
	return TRUE;
}

bool_t
xdr_linked_list(XDR *xdrs, linked_list *objp)
{

	if (!xdr_pointer(xdrs, (char **)&objp->head, sizeof(list_node), (xdrproc_t)xdr_list_node))
		return FALSE;
	if (!xdr_pointer(xdrs, (char **)&objp->tail, sizeof(list_node), (xdrproc_t)xdr_list_node))
		return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_client_token(XDR *xdrs, rpc_client_token *objp)
{

	if (!xdr_int(xdrs, &objp->avl_op))
		return FALSE;
	if (!xdr_int(xdrs, &objp->is_signed))
		return FALSE;
	if (!xdr_vector(xdrs, (char *)objp->permissions, MAX_LEN_LINE,
					sizeof(char), (xdrproc_t)xdr_char))
		return FALSE;
	if (!xdr_vector(xdrs, (char *)objp->token_name, TOKEN_LEN,
					sizeof(char), (xdrproc_t)xdr_char))
		return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_client(XDR *xdrs, rpc_client *objp)
{

	if (!xdr_vector(xdrs, (char *)objp->user_id, MAX_LEN_LINE,
					sizeof(char), (xdrproc_t)xdr_char))
		return FALSE;
	if (!xdr_array(xdrs, (char **)&objp->operation_type.operation_type_val, (u_int *)&objp->operation_type.operation_type_len, ~0,
				   sizeof(string_l), (xdrproc_t)xdr_string_l))
		return FALSE;
	if (!xdr_array(xdrs, (char **)&objp->options.options_val, (u_int *)&objp->options.options_len, ~0,
				   sizeof(string_l), (xdrproc_t)xdr_string_l))
		return FALSE;
	if (!xdr_array(xdrs, (char **)&objp->operations.operations_val, (u_int *)&objp->operations.operations_len, ~0,
				   sizeof(string_l), (xdrproc_t)xdr_string_l))
		return FALSE;
	if (!xdr_rpc_client_token(xdrs, &objp->auth_token))
		return FALSE;
	if (!xdr_rpc_client_token(xdrs, &objp->acc_token))
		return FALSE;
	if (!xdr_rpc_client_token(xdrs, &objp->refresh_token))
		return FALSE;
	return TRUE;
}
